# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 21:50
from __future__ import unicode_literals

import commander.validators
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('wikidata_id', models.CharField(max_length=100, validators=[commander.validators.validate_wikidata_id])),
                ('points', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('revision', models.DateTimeField(auto_now_add=True)),
                ('image_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_texts', to='commander.ImageRequest')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=500, null=True)),
                ('image_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_images', to='commander.ImageRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WikimediaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikimedia_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
